In [17]:
import sqlite3
import pandas as pd

# Connect to an in-memory SQLite database
conn = sqlite3.connect(':memory:')
cursor = conn.cursor()

# Create the employees table
cursor.execute('''
    CREATE TABLE employees (
        id INTEGER PRIMARY KEY,
        name TEXT NOT NULL,
        department TEXT NOT NULL,
        salary REAL NOT NULL
    )
''')

# Insert sample data
employees_data = [
    (1, 'Alice Smith', 'Sales', 75000),
    (2, 'Bob Johnson', 'Marketing', 60000),
    (3, 'Charlie Brown', 'Sales', 80000),
    (4, 'David Lee', 'IT', 90000),
    (5, 'Eve Davis', 'Marketing', 65000),
    (6, 'Frank White', 'IT', 95000),
    (7, 'Grace Taylor', 'Sales', 82000),
    (8, 'Henry Wilson', 'HR', 55000),
    (9, 'Amy Green', 'Marketing', 70000),
    (10, 'Andrew Clark', 'IT', 88000)
]

cursor.executemany('INSERT INTO employees (id, name, department, salary) VALUES (?, ?, ?, ?)', employees_data)
conn.commit()

print("Database and 'employees' table created with sample data.")

Database and 'employees' table created with sample data.

In [18]:
query_starts_with_a = "SELECT name, department, salary FROM employees WHERE name LIKE 'A%'"
employees_starts_with_a = pd.read_sql_query(query_starts_with_a, conn)
print("Employees whose name starts with 'A':")
display(employees_starts_with_a)

Employees whose name starts with 'A':

           name department   salary
0   Alice Smith      Sales  75000.0
1     Amy Green  Marketing  70000.0
2  Andrew Clark         IT  88000.0

In [19]:
print("Original employee departments:")
display(pd.read_sql_query("SELECT id, name, department FROM employees", conn))

# Update department names
cursor.execute("UPDATE employees SET department = 'Customer Relations' WHERE department = 'Sales'")
cursor.execute("UPDATE employees SET department = 'Digital Outreach' WHERE department = 'Marketing'")
conn.commit()

print("\nUpdated employee departments:")
display(pd.read_sql_query("SELECT id, name, department FROM employees", conn))

Original employee departments:

   id           name department
0   1    Alice Smith      Sales
1   2    Bob Johnson  Marketing
2   3  Charlie Brown      Sales
3   4      David Lee         IT
4   5      Eve Davis  Marketing
5   6    Frank White         IT
6   7   Grace Taylor      Sales
7   8   Henry Wilson         HR
8   9      Amy Green  Marketing
9  10   Andrew Clark         IT

Updated employee departments:

   id           name          department
0   1    Alice Smith  Customer Relations
1   2    Bob Johnson    Digital Outreach
2   3  Charlie Brown  Customer Relations
3   4      David Lee                  IT
4   5      Eve Davis    Digital Outreach
5   6    Frank White                  IT
6   7   Grace Taylor  Customer Relations
7   8   Henry Wilson                  HR
8   9      Amy Green    Digital Outreach
9  10   Andrew Clark                  IT

In [20]:
query_top_3 = "SELECT name, department, salary FROM employees ORDER BY salary DESC LIMIT 3"
top_3_employees = pd.read_sql_query(query_top_3, conn)
print("Top 3 highest-paid employees:")
display(top_3_employees)

Top 3 highest-paid employees:

           name department   salary
0   Frank White         IT  95000.0
1     David Lee         IT  90000.0
2  Andrew Clark         IT  88000.0

In [21]:
cursor.execute('''
    CREATE TABLE projects (
        project_id INTEGER PRIMARY KEY,
        project_name TEXT NOT NULL,
        employee_id INTEGER,
        FOREIGN KEY (employee_id) REFERENCES employees(id)
    )
''')

# Insert sample project data
projects_data = [
    (101, 'Website Redesign', 1),
    (102, 'New Marketing Campaign', 2),
    (103, 'Internal Tools Development', 4),
    (104, 'Sales Strategy 2024', 7),
    (105, 'Cloud Migration', 6),
    (106, 'HR System Upgrade', 8),
    (107, 'Customer Feedback Analysis', 5)
]
cursor.executemany('INSERT INTO projects (project_id, project_name, employee_id) VALUES (?, ?, ?)', projects_data)
conn.commit()

print("Created 'projects' table and linked it with 'employees'.")

display(pd.read_sql_query("SELECT * FROM projects", conn))

Created 'projects' table and linked it with 'employees'.

   project_id                project_name  employee_id
0         101            Website Redesign            1
1         102      New Marketing Campaign            2
2         103  Internal Tools Development            4
3         104         Sales Strategy 2024            7
4         105             Cloud Migration            6
5         106           HR System Upgrade            8
6         107  Customer Feedback Analysis            5

In [22]:
cursor.execute("ALTER TABLE employees ADD COLUMN email TEXT")
conn.commit()

# Populate email addresses for existing employees (example)
email_updates = [
    ('alice.smith@example.com', 1),
    ('bob.johnson@example.com', 2),
    ('charlie.brown@example.com', 3),
    ('david.lee@example.com', 4),
    ('eve.davis@example.com', 5),
    ('frank.white@example.com', 6),
    ('grace.taylor@example.com', 7),
    ('henry.wilson@example.com', 8),
    ('amy.green@example.com', 9),
    ('andrew.clark@example.com', 10)
]
cursor.executemany("UPDATE employees SET email = ? WHERE id = ?", email_updates)
conn.commit()

print("Added 'email' column and populated it for existing employees.")
display(pd.read_sql_query("SELECT id, name, department, email, salary FROM employees", conn))

Added 'email' column and populated it for existing employees.

   id           name          department                      email   salary
0   1    Alice Smith  Customer Relations    alice.smith@example.com  75000.0
1   2    Bob Johnson    Digital Outreach    bob.johnson@example.com  60000.0
2   3  Charlie Brown  Customer Relations  charlie.brown@example.com  80000.0
3   4      David Lee                  IT      david.lee@example.com  90000.0
4   5      Eve Davis    Digital Outreach      eve.davis@example.com  65000.0
5   6    Frank White                  IT    frank.white@example.com  95000.0
6   7   Grace Taylor  Customer Relations   grace.taylor@example.com  82000.0
7   8   Henry Wilson                  HR   henry.wilson@example.com  55000.0
8   9      Amy Green    Digital Outreach      amy.green@example.com  70000.0
9  10   Andrew Clark                  IT   andrew.clark@example.com  88000.0